<?php

use Illuminate\Database\Seeder;

use App\Country;

class Countries extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		Country::create(['code' => "AF", 'country' => "Afghanistan"]);
		Country::create(['code' => "AX", 'country' => "&Aring;land Islands"]);
		Country::create(['code' => "AL", 'country' => "Albania"]);
		Country::create(['code' => "DZ", 'country' => "Algeria"]);
		Country::create(['code' => "AS", 'country' => "American Samoa"]);
		Country::create(['code' => "AD", 'country' => "Andorra"]);
		Country::create(['code' => "AO", 'country' => "Angola"]);
		Country::create(['code' => "AI", 'country' => "Anguilla"]);
		Country::create(['code' => "AQ", 'country' => "Antarctica"]);
		Country::create(['code' => "AG", 'country' => "Antigua and Barbuda"]);
		Country::create(['code' => "AR", 'country' => "Argentina"]);
		Country::create(['code' => "AM", 'country' => "Armenia"]);
		Country::create(['code' => "AW", 'country' => "Aruba"]);
		Country::create(['code' => "AU", 'country' => "Australia"]);
		Country::create(['code' => "AT", 'country' => "Austria"]);
		Country::create(['code' => "AZ", 'country' => "Azerbaijan"]);
		Country::create(['code' => "BS", 'country' => "Bahamas"]);
		Country::create(['code' => "BH", 'country' => "Bahrain"]);
		Country::create(['code' => "BD", 'country' => "Bangladesh"]);
		Country::create(['code' => "BB", 'country' => "Barbados"]);
		Country::create(['code' => "BY", 'country' => "Belarus"]);
		Country::create(['code' => "BE", 'country' => "Belgium"]);
		Country::create(['code' => "BZ", 'country' => "Belize"]);
		Country::create(['code' => "BJ", 'country' => "Benin"]);
		Country::create(['code' => "BM", 'country' => "Bermuda"]);
		Country::create(['code' => "BT", 'country' => "Bhutan"]);
		Country::create(['code' => "BO", 'country' => "Bolivia, Plurinational State of"]);
		Country::create(['code' => "BA", 'country' => "Bosnia and Herzegovina"]);
		Country::create(['code' => "BW", 'country' => "Botswana"]);
		Country::create(['code' => "BV", 'country' => "Bouvet Island"]);
		Country::create(['code' => "BR", 'country' => "Brazil"]);
		Country::create(['code' => "IO", 'country' => "British Indian Ocean Territory"]);
		Country::create(['code' => "BN", 'country' => "Brunei Darussalam"]);
		Country::create(['code' => "BG", 'country' => "Bulgaria"]);
		Country::create(['code' => "BF", 'country' => "Burkina Faso"]);
		Country::create(['code' => "BI", 'country' => "Burundi"]);
		Country::create(['code' => "KH", 'country' => "Cambodia"]);
		Country::create(['code' => "CM", 'country' => "Cameroon"]);
		Country::create(['code' => "CA", 'country' => "Canada"]);
		Country::create(['code' => "CV", 'country' => "Cape Verde"]);
		Country::create(['code' => "KY", 'country' => "Cayman Islands"]);
		Country::create(['code' => "CF", 'country' => "Central African Republic"]);
		Country::create(['code' => "TD", 'country' => "Chad"]);
		Country::create(['code' => "CL", 'country' => "Chile"]);
		Country::create(['code' => "CN", 'country' => "China"]);
		Country::create(['code' => "CX", 'country' => "Christmas Island"]);
		Country::create(['code' => "CC", 'country' => "Cocos (Keeling) Islands"]);
		Country::create(['code' => "CO", 'country' => "Colombia"]);
		Country::create(['code' => "KM", 'country' => "Comoros"]);
		Country::create(['code' => "CG", 'country' => "Congo"]);
		Country::create(['code' => "CD", 'country' => "Congo, the Democratic Republic of the"]);
		Country::create(['code' => "CK", 'country' => "Cook Islands"]);
		Country::create(['code' => "CR", 'country' => "Costa Rica"]);
		Country::create(['code' => "CI", 'country' => "C&ocirc;te d'Ivoire"]);
		Country::create(['code' => "HR", 'country' => "Croatia"]);
		Country::create(['code' => "CU", 'country' => "Cuba"]);
		Country::create(['code' => "CY", 'country' => "Cyprus"]);
		Country::create(['code' => "CZ", 'country' => "Czech Republic"]);
		Country::create(['code' => "DK", 'country' => "Denmark"]);
		Country::create(['code' => "DJ", 'country' => "Djibouti"]);
		Country::create(['code' => "DM", 'country' => "Dominica"]);
		Country::create(['code' => "DO", 'country' => "Dominican Republic"]);
		Country::create(['code' => "EC", 'country' => "Ecuador"]);
		Country::create(['code' => "EG", 'country' => "Egypt"]);
		Country::create(['code' => "SV", 'country' => "El Salvador"]);
		Country::create(['code' => "GQ", 'country' => "Equatorial Guinea"]);
		Country::create(['code' => "ER", 'country' => "Eritrea"]);
		Country::create(['code' => "EE", 'country' => "Estonia"]);
		Country::create(['code' => "ET", 'country' => "Ethiopia"]);
		Country::create(['code' => "FK", 'country' => "Falkland Islands (Malvinas)"]);
		Country::create(['code' => "FO", 'country' => "Faroe Islands"]);
		Country::create(['code' => "FJ", 'country' => "Fiji"]);
		Country::create(['code' => "FI", 'country' => "Finland"]);
		Country::create(['code' => "FR", 'country' => "France"]);
		Country::create(['code' => "GF", 'country' => "French Guiana"]);
		Country::create(['code' => "PF", 'country' => "French Polynesia"]);
		Country::create(['code' => "TF", 'country' => "French Southern Territories"]);
		Country::create(['code' => "GA", 'country' => "Gabon"]);
		Country::create(['code' => "GM", 'country' => "Gambia"]);
		Country::create(['code' => "GE", 'country' => "Georgia"]);
		Country::create(['code' => "DE", 'country' => "Germany"]);
		Country::create(['code' => "GH", 'country' => "Ghana"]);
		Country::create(['code' => "GI", 'country' => "Gibraltar"]);
		Country::create(['code' => "GR", 'country' => "Greece"]);
		Country::create(['code' => "GL", 'country' => "Greenland"]);
		Country::create(['code' => "GD", 'country' => "Grenada"]);
		Country::create(['code' => "GP", 'country' => "Guadeloupe"]);
		Country::create(['code' => "GU", 'country' => "Guam"]);
		Country::create(['code' => "GT", 'country' => "Guatemala"]);
		Country::create(['code' => "GG", 'country' => "Guernsey"]);
		Country::create(['code' => "GN", 'country' => "Guinea"]);
		Country::create(['code' => "GW", 'country' => "Guinea-Bissau"]);
		Country::create(['code' => "GY", 'country' => "Guyana"]);
		Country::create(['code' => "HT", 'country' => "Haiti"]);
		Country::create(['code' => "HM", 'country' => "Heard Island and McDonald Islands"]);
		Country::create(['code' => "VA", 'country' => "Holy See (Vatican City State)"]);
		Country::create(['code' => "HN", 'country' => "Honduras"]);
		Country::create(['code' => "HK", 'country' => "Hong Kong"]);
		Country::create(['code' => "HU", 'country' => "Hungary"]);
		Country::create(['code' => "IS", 'country' => "Iceland"]);
		Country::create(['code' => "IN", 'country' => "India"]);
		Country::create(['code' => "ID", 'country' => "Indonesia"]);
		Country::create(['code' => "IR", 'country' => "Iran, Islamic Republic of"]);
		Country::create(['code' => "IQ", 'country' => "Iraq"]);
		Country::create(['code' => "IE", 'country' => "Ireland"]);
		Country::create(['code' => "IM", 'country' => "Isle of Man"]);
		Country::create(['code' => "IL", 'country' => "Israel"]);
		Country::create(['code' => "IT", 'country' => "Italy"]);
		Country::create(['code' => "JM", 'country' => "Jamaica"]);
		Country::create(['code' => "JP", 'country' => "Japan"]);
		Country::create(['code' => "JE", 'country' => "Jersey"]);
		Country::create(['code' => "JO", 'country' => "Jordan"]);
		Country::create(['code' => "KZ", 'country' => "Kazakhstan"]);
		Country::create(['code' => "KE", 'country' => "Kenya"]);
		Country::create(['code' => "KI", 'country' => "Kiribati"]);
		Country::create(['code' => "KP", 'country' => "Korea, Democratic People's Republic of"]);
		Country::create(['code' => "KR", 'country' => "Korea, Republic of"]);
		Country::create(['code' => "KW", 'country' => "Kuwait"]);
		Country::create(['code' => "KG", 'country' => "Kyrgyzstan"]);
		Country::create(['code' => "LA", 'country' => "Lao People's Democratic Republic"]);
		Country::create(['code' => "LV", 'country' => "Latvia"]);
		Country::create(['code' => "LB", 'country' => "Lebanon"]);
		Country::create(['code' => "LS", 'country' => "Lesotho"]);
		Country::create(['code' => "LR", 'country' => "Liberia"]);
		Country::create(['code' => "LY", 'country' => "Libyan Arab Jamahiriya"]);
		Country::create(['code' => "LI", 'country' => "Liechtenstein"]);
		Country::create(['code' => "LT", 'country' => "Lithuania"]);
		Country::create(['code' => "LU", 'country' => "Luxembourg"]);
		Country::create(['code' => "MO", 'country' => "Macao"]);
		Country::create(['code' => "MK", 'country' => "Macedonia, the former Yugoslav Republic of"]);
		Country::create(['code' => "MG", 'country' => "Madagascar"]);
		Country::create(['code' => "MW", 'country' => "Malawi"]);
		Country::create(['code' => "MY", 'country' => "Malaysia"]);
		Country::create(['code' => "MV", 'country' => "Maldives"]);
		Country::create(['code' => "ML", 'country' => "Mali"]);
		Country::create(['code' => "MT", 'country' => "Malta"]);
		Country::create(['code' => "MH", 'country' => "Marshall Islands"]);
		Country::create(['code' => "MQ", 'country' => "Martinique"]);
		Country::create(['code' => "MR", 'country' => "Mauritania"]);
		Country::create(['code' => "MU", 'country' => "Mauritius"]);
		Country::create(['code' => "YT", 'country' => "Mayotte"]);
		Country::create(['code' => "MX", 'country' => "Mexico"]);
		Country::create(['code' => "FM", 'country' => "Micronesia, Federated States of"]);
		Country::create(['code' => "MD", 'country' => "Moldova, Republic of"]);
		Country::create(['code' => "MC", 'country' => "Monaco"]);
		Country::create(['code' => "MN", 'country' => "Mongolia"]);
		Country::create(['code' => "ME", 'country' => "Montenegro"]);
		Country::create(['code' => "MS", 'country' => "Montserrat"]);
		Country::create(['code' => "MA", 'country' => "Morocco"]);
		Country::create(['code' => "MZ", 'country' => "Mozambique"]);
		Country::create(['code' => "MM", 'country' => "Myanmar"]);
		Country::create(['code' => "NA", 'country' => "Namibia"]);
		Country::create(['code' => "NR", 'country' => "Nauru"]);
		Country::create(['code' => "NP", 'country' => "Nepal"]);
		Country::create(['code' => "NL", 'country' => "Netherlands"]);
		Country::create(['code' => "AN", 'country' => "Netherlands Antilles"]);
		Country::create(['code' => "NC", 'country' => "New Caledonia"]);
		Country::create(['code' => "NZ", 'country' => "New Zealand"]);
		Country::create(['code' => "NI", 'country' => "Nicaragua"]);
		Country::create(['code' => "NE", 'country' => "Niger"]);
		Country::create(['code' => "NG", 'country' => "Nigeria"]);
		Country::create(['code' => "NU", 'country' => "Niue"]);
		Country::create(['code' => "NF", 'country' => "Norfolk Island"]);
		Country::create(['code' => "MP", 'country' => "Northern Mariana Islands"]);
		Country::create(['code' => "NO", 'country' => "Norway"]);
		Country::create(['code' => "OM", 'country' => "Oman"]);
		Country::create(['code' => "PK", 'country' => "Pakistan"]);
		Country::create(['code' => "PW", 'country' => "Palau"]);
		Country::create(['code' => "PS", 'country' => "Palestinian Territory, Occupied"]);
		Country::create(['code' => "PA", 'country' => "Panama"]);
		Country::create(['code' => "PG", 'country' => "Papua New Guinea"]);
		Country::create(['code' => "PY", 'country' => "Paraguay"]);
		Country::create(['code' => "PE", 'country' => "Peru"]);
		Country::create(['code' => "PH", 'country' => "Philippines"]);
		Country::create(['code' => "PN", 'country' => "Pitcairn"]);
		Country::create(['code' => "PL", 'country' => "Poland"]);
		Country::create(['code' => "PT", 'country' => "Portugal"]);
		Country::create(['code' => "PR", 'country' => "Puerto Rico"]);
		Country::create(['code' => "QA", 'country' => "Qatar"]);
		Country::create(['code' => "RE", 'country' => "R&eacute;union"]);
		Country::create(['code' => "RO", 'country' => "Romania"]);
		Country::create(['code' => "RU", 'country' => "Russian Federation"]);
		Country::create(['code' => "RW", 'country' => "Rwanda"]);
		Country::create(['code' => "BL", 'country' => "Saint Barth&eacute;lemy"]);
		Country::create(['code' => "SH", 'country' => "Saint Helena, Ascension and Tristan da Cunha"]);
		Country::create(['code' => "KN", 'country' => "Saint Kitts and Nevis"]);
		Country::create(['code' => "LC", 'country' => "Saint Lucia"]);
		Country::create(['code' => "MF", 'country' => "Saint Martin (French part)"]);
		Country::create(['code' => "PM", 'country' => "Saint Pierre and Miquelon"]);
		Country::create(['code' => "VC", 'country' => "Saint Vincent and the Grenadines"]);
		Country::create(['code' => "WS", 'country' => "Samoa"]);
		Country::create(['code' => "SM", 'country' => "San Marino"]);
		Country::create(['code' => "ST", 'country' => "Sao Tome and Principe"]);
		Country::create(['code' => "SA", 'country' => "Saudi Arabia"]);
		Country::create(['code' => "SN", 'country' => "Senegal"]);
		Country::create(['code' => "RS", 'country' => "Serbia"]);
		Country::create(['code' => "SC", 'country' => "Seychelles"]);
		Country::create(['code' => "SL", 'country' => "Sierra Leone"]);
		Country::create(['code' => "SG", 'country' => "Singapore"]);
		Country::create(['code' => "SK", 'country' => "Slovakia"]);
		Country::create(['code' => "SI", 'country' => "Slovenia"]);
		Country::create(['code' => "SB", 'country' => "Solomon Islands"]);
		Country::create(['code' => "SO", 'country' => "Somalia"]);
		Country::create(['code' => "ZA", 'country' => "South Africa"]);
		Country::create(['code' => "GS", 'country' => "South Georgia and the South Sandwich Islands"]);
		Country::create(['code' => "ES", 'country' => "Spain"]);
		Country::create(['code' => "LK", 'country' => "Sri Lanka"]);
		Country::create(['code' => "SD", 'country' => "Sudan"]);
		Country::create(['code' => "SR", 'country' => "Suriname"]);
		Country::create(['code' => "SJ", 'country' => "Svalbard and Jan Mayen"]);
		Country::create(['code' => "SZ", 'country' => "Swaziland"]);
		Country::create(['code' => "SE", 'country' => "Sweden"]);
		Country::create(['code' => "CH", 'country' => "Switzerland"]);
		Country::create(['code' => "SY", 'country' => "Syrian Arab Republic"]);
		Country::create(['code' => "TW", 'country' => "Taiwan, Province of China"]);
		Country::create(['code' => "TJ", 'country' => "Tajikistan"]);
		Country::create(['code' => "TZ", 'country' => "Tanzania, United Republic of"]);
		Country::create(['code' => "TH", 'country' => "Thailand"]);
		Country::create(['code' => "TL", 'country' => "Timor-Leste"]);
		Country::create(['code' => "TG", 'country' => "Togo"]);
		Country::create(['code' => "TK", 'country' => "Tokelau"]);
		Country::create(['code' => "TO", 'country' => "Tonga"]);
		Country::create(['code' => "TT", 'country' => "Trinidad and Tobago"]);
		Country::create(['code' => "TN", 'country' => "Tunisia"]);
		Country::create(['code' => "TR", 'country' => "Turkey"]);
		Country::create(['code' => "TM", 'country' => "Turkmenistan"]);
		Country::create(['code' => "TC", 'country' => "Turks and Caicos Islands"]);
		Country::create(['code' => "TV", 'country' => "Tuvalu"]);
		Country::create(['code' => "UG", 'country' => "Uganda"]);
		Country::create(['code' => "UA", 'country' => "Ukraine"]);
		Country::create(['code' => "AE", 'country' => "United Arab Emirates"]);
		Country::create(['code' => "GB", 'country' => "United Kingdom"]);
		Country::create(['code' => "US", 'country' => "United States"]);
		Country::create(['code' => "UM", 'country' => "United States Minor Outlying Islands"]);
		Country::create(['code' => "UY", 'country' => "Uruguay"]);
		Country::create(['code' => "UZ", 'country' => "Uzbekistan"]);
		Country::create(['code' => "VU", 'country' => "Vanuatu"]);
		Country::create(['code' => "VE", 'country' => "Venezuela, Bolivarian Republic of"]);
		Country::create(['code' => "VN", 'country' => "Viet Nam"]);
		Country::create(['code' => "VG", 'country' => "Virgin Islands, British"]);
		Country::create(['code' => "VI", 'country' => "Virgin Islands, U.S."]);
		Country::create(['code' => "WF", 'country' => "Wallis and Futuna"]);
		Country::create(['code' => "EH", 'country' => "Western Sahara"]);
		Country::create(['code' => "YE", 'country' => "Yemen"]);
		Country::create(['code' => "ZM", 'country' => "Zambia"]);
		Country::create(['code' => "ZW", 'country' => "Zimbabwe"]);
    }
}
