<?php

use Illuminate\Database\Seeder;
use App\Curriculum;
use App\Course;

class CoursesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $cur2008 = new Curriculum();
		$cur2008->title = "2008";
		$cur2008->save();

		$cur2013 = new Curriculum();
		$cur2013->title = "2013";
		$cur2013->save();


		$course = new Course();$course->curriculum_id = 1;$course->code = "FI1101";$course->title_en = "Elementary Physics IA";$course->semester = 1;$course->rex = "R";$course->sch = 4;$course->mbs = 4;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "FI1201";$course->title_en = "Elementary Physics IIA";$course->semester = 2;$course->rex = "R";$course->sch = 4;$course->mbs = 4;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KI1101";$course->title_en = "Basic Chemistry I A";$course->semester = 1;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KI1201";$course->title_en = "Basic Chemistry II A";$course->semester = 2;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1001";$course->title_en = "Sports";$course->semester = 1;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1011";$course->title_en = "Indonesian Language: Scientific Writing ";$course->semester = 1;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1021";$course->title_en = "English: Critical Reading Skills";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1022";$course->title_en = "English: Writing for Academic Purpose";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1023";$course->title_en = "English: Presentation Technique";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1072";$course->title_en = "Introduction to Information Technology B";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1101";$course->title_en = "Conceptual Science";$course->semester = 1;$course->rex = "R";$course->sch = 2;$course->mbs = 2;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1201";$course->title_en = "Natural and Universe System";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 2;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU1287";$course->title_en = "Introduction to Industrial Technology";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU2061";$course->title_en = "Islam: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU2062";$course->title_en = "Protestant: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU2063";$course->title_en = "Catholic: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU2064";$course->title_en = "Hindu: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU2065";$course->title_en = "Budha: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "KU2071";$course->title_en = "Pancasila & Civic Education";$course->semester = 8;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "MA1101";$course->title_en = "Calculus I";$course->semester = 1;$course->rex = "R";$course->sch = 4;$course->mbs = 4;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "MA1201";$course->title_en = "Calculus II";$course->semester = 2;$course->rex = "R";$course->sch = 4;$course->mbs = 4;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2101";$course->title_en = "System Engineering Mathematics I";$course->semester = 3;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2102";$course->title_en = "Probability and Statistics";$course->semester = 3;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2103";$course->title_en = "Mechanics of Material";$course->semester = 3;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2104";$course->title_en = "Thermodynamics";$course->semester = 3;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2105";$course->title_en = "Electric Circuit and Electronics";$course->semester = 3;$course->rex = "R";$course->sch = 4;$course->mbs = 0;$course->et = 4;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2106";$course->title_en = "Energy Conversion";$course->semester = 3;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2107";$course->title_en = "Engineering Physics Laboratory I";$course->semester = 3;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 1;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2201";$course->title_en = "System Engineering Mathematics II";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2202";$course->title_en = "Engineering Computation";$course->semester = 4;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2203";$course->title_en = "Digital and Logic Systems";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2204";$course->title_en = "Fluid Mechanics";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2205";$course->title_en = "Quantum Physics and Nano";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2206";$course->title_en = "Electromagnetic Fields";$course->semester = 4;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF2207";$course->title_en = "Engineering Physics Laboratory II";$course->semester = 4;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 1;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3101";$course->title_en = "System Dynamics and Simulation";$course->semester = 5;$course->rex = "R";$course->sch = 2;$course->mbs = 2;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3102";$course->title_en = "Measurement Methods";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3103";$course->title_en = "Wave Phenomena";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3104";$course->title_en = "Physics of Materials";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3105";$course->title_en = "Heat and Mass Transfer";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3106";$course->title_en = "Engineering Physics Laboratory III";$course->semester = 5;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 1;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3201";$course->title_en = "Signal Processing";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3202";$course->title_en = "Automatic Control";$course->semester = 6;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3203";$course->title_en = "Sensors and Actuators";$course->semester = 6;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3204";$course->title_en = "Acoustics";$course->semester = 6;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3205";$course->title_en = "Thermal Analysis";$course->semester = 6;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF3206";$course->title_en = "Engineering Physics Laboratory IV";$course->semester = 6;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 1;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4001";$course->title_en = "Engineering Ethics & In. Job Training";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4002";$course->title_en = "Capita Selecta of Eengineering Physics";$course->semester = 8;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 0;$course->ge = 1;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4091";$course->title_en = "Final Project ";$course->semester = 8;$course->rex = "R";$course->sch = 5;$course->mbs = 0;$course->et = 5;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4101";$course->title_en = "Building Physics";$course->semester = 7;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4103";$course->title_en = "Laser and Fiber Optics";$course->semester = 7;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4111";$course->title_en = "Imaging Techniques";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4112";$course->title_en = "Modern Control";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4113";$course->title_en = "Digital Control";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4114";$course->title_en = "Optics";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4115";$course->title_en = "Energy Conservation";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4117";$course->title_en = "Material Science and Simulation";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4118";$course->title_en = "Thermal Enviromental Engineering";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4118";$course->title_en = "Material Processing Technology";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4120";$course->title_en = "Digital Spectral Analysis";$course->semester = 7;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 1;$course->code = "TF4201";$course->title_en = "Industrial Instrumentation & Control";$course->semester = 8;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "FI1101";$course->title_en = "Elementary Physics IA";$course->semester = 1;$course->rex = "R";$course->sch = 4;$course->mbs = 4;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "FI1201";$course->title_en = "Elementary Physics IIA";$course->semester = 2;$course->rex = "R";$course->sch = 4;$course->mbs = 4;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KI1101";$course->title_en = "Basic Chemistry IA";$course->semester = 1;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KI1201";$course->title_en = "Basic Chemistry II A";$course->semester = 2;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1001";$course->title_en = "Sports";$course->semester = 1;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1011";$course->title_en = "Indonesian Language";$course->semester = 1;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1021";$course->title_en = "English: Reading for Academic Purpose";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1022";$course->title_en = "English: Writing for Academic Purpose";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1023";$course->title_en = "English: Presentation Skills";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1072";$course->title_en = "Intro to Information Technology B";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1101";$course->title_en = "Intro to Engineering and Design I";$course->semester = 1;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1201";$course->title_en = "Intro to Engineering and Design II";$course->semester = 2;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU1267";$course->title_en = "Engineering Drawing";$course->semester = 1;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU2061";$course->title_en = "Islam: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU2062";$course->title_en = "Protestant: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU2063";$course->title_en = "Catholic: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU2064";$course->title_en = "Hindu: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU2065";$course->title_en = "Budha: Religion and Ethics";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU2071";$course->title_en = "Pancasila and Civic Education";$course->semester = 8;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU4078";$course->title_en = "Studium Generale";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU4172";$course->title_en = "Labor Law";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU4183";$course->title_en = "Sociology of Industry";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU4281";$course->title_en = "Controversy of Social Issues";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "MA1101";$course->title_en = "Mathematics IA";$course->semester = 1;$course->rex = "R";$course->sch = 4;$course->mbs = 4;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "MA1201";$course->title_en = "Mathematics IIA";$course->semester = 2;$course->rex = "R";$course->sch = 4;$course->mbs = 4;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "ME4014";$course->title_en = "Wind and Solar Energy";$course->semester = 7;$course->rex = "X";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "ME4034";$course->title_en = "Climate Policy";$course->semester = 7;$course->rex = "X";$course->sch = 3;$course->mbs = 0;$course->et = 0;$course->ge = 3;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "MR4004";$course->title_en = "Engineering Management";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2101";$course->title_en = "Engineering Mathematics I";$course->semester = 3;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2102";$course->title_en = "Probability and Statistics";$course->semester = 3;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2103";$course->title_en = "Mechanics of Material";$course->semester = 3;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2104";$course->title_en = "Thermodynamics";$course->semester = 3;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2105";$course->title_en = "Electric Circuit and Electronics";$course->semester = 3;$course->rex = "R";$course->sch = 4;$course->mbs = 0;$course->et = 4;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2106";$course->title_en = "Electromagnetics";$course->semester = 3;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2107";$course->title_en = "Engineering Physics Laboratory I";$course->semester = 3;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 1;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2201";$course->title_en = "Engineering Mathematics II";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2202";$course->title_en = "Engineering Computation";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2203";$course->title_en = "Digital and Logic Systems";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2204";$course->title_en = "Fluid Mechanics";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2205";$course->title_en = "Wave Phenomena";$course->semester = 4;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2206";$course->title_en = "Energy Conversion";$course->semester = 4;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF2207";$course->title_en = "Engineering Physics Laboratory II";$course->semester = 4;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 1;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3101";$course->title_en = "System Dynamics and Simulation";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 3;$course->et = 0;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3102";$course->title_en = "Measurement Methods";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3103";$course->title_en = "Quantum Mechanics ";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3104";$course->title_en = "Sensor and Actuator";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3105";$course->title_en = "Heat and Mass Transfer";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3106";$course->title_en = "Engineering Physics Laboratory III";$course->semester = 5;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 1;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3107";$course->title_en = "Signal Processing";$course->semester = 5;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3201";$course->title_en = "Physics of Materials";$course->semester = 6;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3202";$course->title_en = "Environment and Energy";$course->semester = 6;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3203";$course->title_en = "Automatic Control";$course->semester = 6;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3204";$course->title_en = "Acoustics";$course->semester = 6;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3205";$course->title_en = "Thermal Systems Design";$course->semester = 6;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF3206";$course->title_en = "Engineering Physics Laboratory IV";$course->semester = 6;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 1;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4001";$course->title_en = "Engineering Ethics and Industrial Job Training";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4002";$course->title_en = "Capita Selecta of Engineering Physics";$course->semester = 8;$course->rex = "R";$course->sch = 1;$course->mbs = 0;$course->et = 0;$course->ge = 1;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4010";$course->title_en = "Building Physics";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4011";$course->title_en = "Thermal Enviromental Engineering";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4012";$course->title_en = "Lighting Engineering";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4013";$course->title_en = "Energy Conservation";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4014";$course->title_en = "Energy Systems";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4020";$course->title_en = "Laser and Fiber Optics";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4021";$course->title_en = "Optic Techniques";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4022";$course->title_en = "Medical Physics";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4023";$course->title_en = "Industrial Instrumentation and Control";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4024";$course->title_en = "Imaging Techniques";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4025";$course->title_en = "Ultrasonic";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4026";$course->title_en = "Modern Control";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4027";$course->title_en = "Digital Control";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4028";$course->title_en = "Intelligent Control Systems";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4029";$course->title_en = "Robust Hybrid Control";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4030";$course->title_en = "Material Processing Technology";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4031";$course->title_en = "Materials Characterization Techniques";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4032";$course->title_en = "Material Science Simulation";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "BI4105";$course->title_en = "Neurobiology";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TI3004";$course->title_en = "Engineering Economics";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "IK5007";$course->title_en = "Mechatronics and Robotics";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4091";$course->title_en = "Design and Experimental Methods";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4092";$course->title_en = "Final Project and Comprehensive Examination";$course->semester = 8;$course->rex = "R";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4101";$course->title_en = "Engineering Physics Multi Disciplinary Project";$course->semester = 7;$course->rex = "R";$course->sch = 2;$course->mbs = 0;$course->et = 2;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4042";$course->title_en = "Special Topic B";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4033";$course->title_en = "Statistical Thermodynamics";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF5022";$course->title_en = "Electronic Materials";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TI4104";$course->title_en = "Enterprise Development and Entrepreneurship ";$course->semester = 8;$course->rex = "X";$course->sch = 3;$course->mbs = 0;$course->et = 0;$course->ge = 3;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF5031";$course->title_en = "SCADA Systems";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU4074";$course->title_en = "Politics and Governance";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "TF4041";$course->title_en = "Special Topic A";$course->semester = 8;$course->rex = "E";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU4095";$course->title_en = "Entrepreneurship";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "IK5009";$course->title_en = "Industrial Automation Systems";$course->semester = 8;$course->rex = "X";$course->sch = 3;$course->mbs = 0;$course->et = 3;$course->ge = 0;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU4013";$course->title_en = "Appreciation of Literature";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
$course = new Course();$course->curriculum_id = 2;$course->code = "KU4184";$course->title_en = "Anthropology";$course->semester = 8;$course->rex = "X";$course->sch = 2;$course->mbs = 0;$course->et = 0;$course->ge = 2;$course->save();
	
    }
}
